# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Office', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='Office',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='listings.Site'),
            preserve_default=False,
        ),
    ]
