# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20161109_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='Office',
            field=models.CharField(max_length=200),
        ),
    ]
