# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('listings', '0007_auto_20161110_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Office', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Team'),
        ),
    ]
