# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('listings', '0008_auto_20161110_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
