# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('listings', '0009_auto_20161110_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='commission',
            new_name='commission_rate',
        ),
        migrations.AddField(
            model_name='listing',
            name='commission_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
